## Problem Set 5 - PHYS 305, Fall 2020
#### Due on Oct 20, 5 pm on D2L
This problem set contains 3 problems. You can submit either a completed notebook, _or_ a compressed folder containing python code (to be run from the command line) and write ups.

### Problem 1: A Python Class for Matrices [15 points]

In [1]:
class Matrix:
    def set_from_list(self, listoflists):
        self.elements = listoflists;
        return self
    def print(self):
        for row in self.elements:
            print("[", end="")
            for element in row:
                print("%3s" % element, end=" ")
            print("]")
    def multiply_m(self, other):
        product = Matrix()
        
        n = len(self.elements)
        m = len(self.elements[0])
        otherN = len(other.elements)
        otherM = len(other.elements[0])
        
        if (m != otherN):
            raise ValueError("Cannot multiply a %dx%d matrix by a %dx%d matrix." % (n, m, otherN, otherM))
        
        elements = []
        for i in range(n):
            elements.append([])
            for j in range(otherM):
                elements[i].append(0)
                for k in range(m):
                    elements[i][j] += self.elements[i][k] * other.elements[k][j]
        product.set_from_list(elements)
        
        return product
    def multiply_s(self, s):
        product = Matrix()
        
        elements = [[3 * elem for elem in row] for row in self.elements]
        product.set_from_list(elements)
        
        return product
    
A = Matrix()
A.set_from_list([[1, 2, 3], [4, 5, 0], [6, 0, 0]])
B = Matrix()
B.set_from_list([[1, 0], [0, 1], [0, 0]])

print("3A:")
A.multiply_s(3).print()
print("AB:")
A.multiply_m(B).print()
print("BA:")
try:
    B.multiply_m(A).print()
except ValueError as ex:
    print(ex)

3A:
[  3   6   9 ]
[ 12  15   0 ]
[ 18   0   0 ]
AB:
[  1   2 ]
[  4   5 ]
[  6   0 ]
BA:
Cannot multiply a 3x2 matrix by a 3x3 matrix.


### Problem 2: Project Operator Practice [5 points]

Let $P$ be a projection operator. Show that complement $I - P$ is also a projection operator.

_You do not need to write code for this problem!_
## Solution
We can show that this a projector by examining a repeated application of $(I-P)$:
$$\begin{aligned}
    (I - P)^2 &= I - IP - IP + P^2 \\
    &= I - 2 P + P^2 \\
    &= I - 2P + P \\
    &= I - P.
\end{aligned}$$

### Problem 3: QR Decomposition [10 points]

Implement the __modified Gram-Schmidt__ algorithm from Lecture 20, and compare $Q*R - A$ for your implementation and the routine `classic_GS` (demonstrated in Lecture 20) for the matrix
$$ A = \begin{bmatrix} 1 & 1 & 1\\ 
                       1 & 1 & 0\\ 
                       1 & 0 & 0 
        \end{bmatrix}\,.
$$



In [4]:
# Classical Gram-Schmidt Iteration from Lecture 20
import numpy
def classic_GS(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = numpy.empty((m, n))
    R = numpy.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = numpy.dot(Q[:, i].conjugate(), A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = numpy.linalg.norm(v, ord=2)
        Q[:, j] = v / R[j, j]
    return Q, R


def mod_GS(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = numpy.empty((m, n))
    R = numpy.zeros((n, n))
    v = A.copy()
    for i in range(n):
        R[i, i] = numpy.linalg.norm(v[:, i], ord=2)
        Q[:, i] = v[:, i] / R[i, i]
        for j in range(i + 1, n):
            R[i, j] = numpy.dot(Q[:, i].conjugate(), v[:, j])
            v[:, j] -= R[i, j] * Q[:, i]
    return Q, R
A = numpy.array([[1.,1.,1.],[1.,1.,0.], [1.,0.,0.]])
Q, R = classic_GS(A)
print("Classic = ")
print(numpy.dot(Q, R) - A)
Q, R = mod_GS(A)
print("Modified = ")
print(numpy.dot(Q, R) - A)

Classic = 
[[ 0.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00 -2.23711432e-17]
 [ 0.00000000e+00  9.17267705e-19  1.52238409e-17]]
Modified = 
[[ 0.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.01465364e-17]
 [ 0.00000000e+00  9.17267705e-19  4.58633852e-19]]
